version: "3.7"

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
    command: "yarn preview"
    networks:
      - nuxt-network
  web-server:
    image: nginx:latest
    container_name: web-server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      nuxt-network:
    depends_on:
      - nuxt-app
    restart: unless-stopped
networks:
  nuxt-network:
    driver: bridge
